name: OrderPdf
event: OrderPdf
code: OrderPdf
version: 0.0.1
service:
    - OrderPdfServiceProvider
orm.path:
    - /Resource/doctrine
#form:
#    onSetData:
#        Form\Type\PaymentFragmentForm
