name: OrderPdf
event: OrderPdfEvent
code: OrderPdf
version: 1.0.0
service:
    - OrderPdfServiceProvider
orm.path:
    - /Resource/doctrine
const:
    logo_file: logo.png
    pdf_file: nouhinsyo1.pdf
    order_pdf_message_len: 30
